# Site settings
title: PAO'S BLOG
description: "可別對我有過度的想像，我可沒有什麼都會（冒汗），即使是資訊科學領域 。我只是有個能力叫很高的學習力，讓人覺得我「似乎什麼都會，只是有點慢」（倒）"
baseurl: ""
url: "" # https://flashaim-pao.github.io

# User settings
username: Pao
user_title: PAO'S Profile
email: paowang@flashaim.com
github_username:  flashaim-pao
linkedin_public_url: pao-yao-wang-1524b350 
#twitter_username: loremipsum
#gplus_username:  loremipsum
disqus_username: ld-pao0111
profile_picture: https://s3.amazonaws.com/logdown-production/system/blog/5862/og_image/pao3.jpeg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/flashaim-pao
      new_tab: true
      key_trigger: g
    - title: flashaim
      url: http://flashaim.com
      key_trigger: f
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
# projects:
  # - name: fluany
  #   url: https://github.com/fluany/fluany
  # - name: vim-frontend
  #   url: https://github.com/victorvoid/vim-frontend
  # - name: generator-capybara
  #   url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
